version: "3.1"

services:
  websocket:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: websocket
    restart: always
    command: python /web_sockets.py
    env_file: ./env/secrets.env
